blank_issues_enabled: true
contact_links:
    - name: Q&A Help
      url: https://github.com/st3v3nmw/obsidian-spaced-repetition/discussions/categories/q-a
      about: Please ask and answer questions here.
    - name: Discussion
      url: https://github.com/st3v3nmw/obsidian-spaced-repetition/discussions
      about: Please use GitHub Discussions for general discussions, feedback, and release discussions.
